DROP TABLE telefone;
DROP TABLE usuarios;

CREATE TABLE IF NOT EXISTS telefone(
	id BIGSERIAL NOT NULL, 
	ddd BIGINT NOT NULL, 
	numero VARCHAR(15) NOT NULL, 
	tipo VARCHAR(20) NOT NULL, 
	idUsuario BIGINT NOT NULL, 
	PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS usuarios(
	id BIGSERIAL NOT NULL, 
	nome VARCHAR(255) NOT NULL, 
	email VARCHAR(255) NOT NULL UNIQUE, 
	senha VARCHAR(50) NOT NULL, 
	PRIMARY KEY (id));

ALTER TABLE telefone ADD CONSTRAINT fk_idusuario 
FOREIGN KEY (idUsuario) REFERENCES usuarios(id);
